# Use root/example user/password credentials
version: '3.7'

services:
  rest:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: restapi
    ports:
      - "81:80"
    volumes:
      - ./data_storage_rest:/var/www/html/
    networks:
      new_nw:
        ipv4_address: 192.168.1.3

  php_app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: php_app
    ports:
      - "80:80"
    volumes:
      - ./php_app:/var/www/html/
    networks:
      new_nw:
        ipv4_address: 192.168.1.4


  mongo_data_con:
    image: mongo:latest
    restart: always
    container_name: mongo_data_con
    hostname: mongo_data_con
    ports:
      - "27018:27017"
    volumes: 
      - mongo_data_db:/data/db  
    networks:
        new_nw:
          ipv4_address: 192.168.1.5
     
  mongo_seed:
      container_name: mongo_seed
      image: mongo:latest
      links:
        - mongo_data_con
      volumes:
      - ./mongo-seed:/mongo-seed
      command:
        /mongo-seed/import.sh
      networks:
          new_nw:
            ipv4_address: 192.168.1.6

  mysql:
      image: mysql:5.7
      hostname: mysql
      container_name: mysql
      restart: always
      expose:
          - '3306'
      ports:
          - '3306:3306'
      networks:
          new_nw:
              ipv4_address: 192.168.1.8
      environment:
          - 'MYSQL_ROOT_PASSWORD=secret'
          - 'MYSQL_ROOT_HOST=192.168.1.7'
          - 'MYSQL_DATABASE=idm'
      volumes:
          - mysql_db:/var/lib/mysql
          - ./Keyrock_mysql_backup:/docker-entrypoint-initdb.d 
          
          
  keyrock:
      image: fiware/idm:latest
      container_name: keyrock
      hostname: keyrock
      depends_on:
        - mysql
      ports:
        - "3005:3005"
      environment:
        - DEBUG=idm:*
        - IDM_DB_HOST=mysql
        - IDM_DB_PASS=secret
        - IDM_DB_USER=root
        - IDM_HOST=http://localhost:3005
        - IDM_PORT=3005
        - IDM_ADMIN_USER=admin
        - IDM_ADMIN_EMAIL=admin@test.com
        - IDM_ADMIN_PASS=1234
      networks:
            new_nw:
                ipv4_address: 192.168.1.7


  restProxy:
      image: fiware/pep-proxy 
      container_name: restProxy
      depends_on:
        - keyrock
      ports:
        - "1030:1027"
      expose: 
        - "1030"
      environment: 
        - PEP_PROXY_APP_HOST=restapi
        - PEP_PROXY_APP_PORT=80
        - PEP_PROXY_PORT=1030
        - PEP_PROXY_IDM_HOST=keyrock
        - PEP_PROXY_HTTPS_ENABLED=false
        - PEP_PROXY_AUTH_ENABLED=false
        - PEP_PROXY_IDM_SSL_ENABLED=false
        - PEP_PROXY_IDM_PORT=3005
        - PEP_PROXY_APP_ID=ce9c1647-2028-4513-8dd5-6de8ef502de4
        - PEP_PROXY_USERNAME=pep_proxy_8923f0d0-5516-4492-a9fc-90d120d889f9
        - PEP_PASSWORD=pep_proxy_684a8274-a535-4969-b926-0dffc78a85f8
        - PEP_PROXY_PDP=idm
        - PEP_PROXY_MAGIC_KEY=Secret_key
      networks:
        new_nw:
            ipv4_address: 192.168.1.9


  orion_mongo:
      image: mongo:3.6
      container_name: orion_mongo
      hostname: orion_mongo
      ports: 
        - '27017:27017'
      volumes: 
        - mongo_orion:/data/db
      command: --nojournal
      networks:
        new_nw:
          ipv4_address: 192.168.1.15


  orionBroker:
      image: fiware/orion
      links:
        - orion_mongo
      command: -dbhost orion_mongo -logLevel DEBUG
      container_name: orionBroker
      hostname: orionBroker
      ports:
        - "1026:1026"
      expose:
        - "1026"
      networks:
        new_nw:
          ipv4_address: 192.168.1.12


  orionProxy:
      image: fiware/pep-proxy 
      container_name: orionProxy
      depends_on:
        - keyrock
      ports:
        - "1029:1027"
      expose:
        - "1029"
      environment: 
        - PEP_PROXY_APP_HOST=orionBroker
        - PEP_PROXY_APP_PORT=1026
        - PEP_PROXY_PORT=1029
        - PEP_PROXY_IDM_HOST=keyrock
        - PEP_PROXY_HTTPS_ENABLED=false
        - PEP_PROXY_AUTH_ENABLED=false
        - PEP_PROXY_IDM_SSL_ENABLED=false
        - PEP_PROXY_IDM_PORT=3005
        - PEP_PROXY_APP_ID=ce9c1647-2028-4513-8dd5-6de8ef502de4
        - PEP_PROXY_USERNAME=pep_proxy_8923f0d0-5516-4492-a9fc-90d120d889f9
        - PEP_PASSWORD=pep_proxy_684a8274-a535-4969-b926-0dffc78a85f8
        - PEP_PROXY_PDP=idm
        - PEP_PROXY_MAGIC_KEY=Secret_key
      networks:
        new_nw:
          ipv4_address: 192.168.1.13





networks:
  new_nw:
    ipam:
      config:
        - subnet: 192.168.1.0/24
volumes: 
  mongo_data_db:
  mysql_db:
  mongo_orion:
